"""add icon to seasons and places

Revision ID: 5765da7e24d9
Revises: 12f94bce7091
Create Date: 2026-08-30 01:42:38.487127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5765da7e24d9'
down_revision: Union[str, Sequence[str], None] = '12f94bce7091'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('icon', sa.String(), nullable=True))
    op.add_column('seasons', sa.Column('icon', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seasons', 'icon')
    op.drop_column('places', 'icon')
    # ### end Alembic commands ###
